server:
  host: "127.0.0.1"
  port: 8080
  server_name: "localhost"
  root: "/var/www/html"
  index: "index.html"
  error_pages:
    404: "/errors/404.html"
    500: "/errors/500.html"
  client_max_body_size: 10M

  routes:
    - path: "/"
      methods: ["GET", "POST"]
      root: "/var/www/html"
      directory_listing: false

    - path: "/upload"
      methods: ["POST"]
      root: "/var/www/uploads"
      upload_enabled: true

    - path: "/redirect"
      methods: ["GET"]
      redirect: "https://example.com"